version: '3.1'

services:
  mariadb:
    image: mariadb:11
    container_name: my-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: study!
      MARIADB_DATABASE: jpa_db
      MARIADB_USER: study
      MARIADB_PASSWORD: study
    volumes:
      - ./data:/var/lib/mysql
